---
# TODO Chocolatey Package is currently awaiting release
#- include_tasks: install_windows.yml
#  when: ansible_os_family == "Windows"

- include_tasks: install_unix_debian.yml
  when: ansible_os_family == "Debian"
