---
# TODO Chocolatey Package is currently awaiting release
#- name: Install OCS Inventory NG Windows Agent
#  include_tasks: install_windows.yml
#  when: ansible_os_family == "Windows"

- name: Install OCS Inventory NG Unix Agent (Debian/Ubuntu)
  include_tasks: install_unix_debian.yml
  when: ansible_os_family == "Debian"
